# Generated by Django 2.1.5 on 2019-03-18 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='list',
            field=models.ForeignKey(default=None, on_delete=models.TextField(default=''), to='lists.List'),
        ),
    ]
